name: Qodana Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  qodana:
    name: Qodana for JVM  # <--- THÊM DÒNG NÀY: Phải khớp 100% với tên trong hình của bạn
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # Đừng quên Token như lỗi log nãy nhé